const { SongLib } = require('../models');

const songData = [
  {
    song: 'Bohemian Rhapsody',
    artist: 'Queen',
    album: 'A Night at the Opera',
    rating: 4,
    playlist_id: 1,
  },
  {
    song: 'Super Sharp Shooter',
    artist: 'DJ Zinc',
    album: 'Super Sharp Shooter / So Damn Fresh',
    rating: 4,
    playlist_id: 2,
  },
  {
    song: 'Never Gonna Give You Up',
    artist: 'Rick Astley',
    album: 'Whenever You Need Somebody',
    rating: 5,
    playlist_id: 3,
  },
  {
    song: 'I Walk the Line',
    artist: 'Johnny Cash',
    album: 'I Walk the Line',
    rating: 5,
    playlist_id: 3,
  },
  {
    song: 'Jolene',
    artist: 'Dolly Parton',
    album: 'Jolene',
    rating: 4,
    playlist_id: 6,
  },
  {
    song: 'Friends in Low Places',
    artist: 'Garth Brooks',
    album: 'No Fences',
    rating: 4,
    playlist_id: 1,
  },
  {
    song: 'Stand by Your Man',
    artist: 'Tammy Wynette',
    album: 'Stand by Your Man',
    rating: 4,
    playlist_id: 7,
  },
  {
    song: 'Ring of Fire',
    artist: 'Johnny Cash',
    album: 'Ring of Fire: The Best of Johnny Cash',
    rating: 5,
    playlist_id: 2,
  },
  {
    song: 'Take Me Home, Country Roads',
    artist: 'John Denver',
    album: 'Poems, Prayers & Promises',
    rating: 5,
    playlist_id: 8,
  },
  {
    song: 'Achy Breaky Heart',
    artist: 'Billy Ray Cyrus',
    album: 'Some Gave All',
    rating: 3,
    playlist_id: 9,
  },
  {
    song: 'The Gambler',
    artist: 'Kenny Rogers',
    album: 'The Gambler',
    rating: 4,
    playlist_id: 4,
  },
  {
    song: 'Mama Tried',
    artist: 'Merle Haggard',
    album: 'Mama Tried',
    rating: 4,
    playlist_id: 5,
  },
  {
    song: "Your Cheatin' Heart",
    artist: 'Hank Williams',
    album: "Hank Williams' Greatest Hits",
    rating: 4,
    playlist_id: 10,
  },
  {
    song: 'He Stopped Loving Her Today',
    artist: 'George Jones',
    album: 'I Am What I Am',
    rating: 5,
    playlist_id: 3,
  },
  {
    song: 'Folsom Prison Blues',
    artist: 'Johnny Cash',
    album: 'With His Hot and Blue Guitar',
    rating: 5,
    playlist_id: 6,
  },
  {
    song: 'Man! I Feel Like a Woman!',
    artist: 'Shania Twain',
    album: 'Come On Over',
    rating: 4,
    playlist_id: 2,
  },
  {
    song: 'I Hope You Dance',
    artist: 'Lee Ann Womack',
    album: 'I Hope You Dance',
    rating: 4,
    playlist_id: 8,
  },
  {
    song: 'Forever and Ever, Amen',
    artist: 'Randy Travis',
    album: 'Always & Forever',
    rating: 4,
    playlist_id: 1,
  },
  {
    song: "Coal Miner's Daughter",
    artist: 'Loretta Lynn',
    album: "Coal Miner's Daughter",
    rating: 5,
    playlist_id: 7,
  },
  {
    song: 'Whiskey Lullaby',
    artist: 'Brad Paisley ft. Alison Krauss',
    album: 'Mud on the Tires',
    rating: 4,
    playlist_id: 4,
  },
  {
    song: 'Before He Cheats',
    artist: 'Carrie Underwood',
    album: 'Some Hearts',
    rating: 4,
    playlist_id: 9,
  },
  {
    song: 'I Will Always Love You',
    artist: 'Dolly Parton',
    album: 'Jolene',
    rating: 5,
    playlist_id: 10,
  },
  {
    song: 'When You Say Nothing at All',
    artist: 'Alison Krauss',
    album: "Now That I've Found You: A Collection",
    rating: 5,
    playlist_id: 5,
  },
  {
    song: 'The Faded Line',
    artist: 'Lamb Of God',
    album: 'Ashes Of The Wake',
    rating: 4,
    playlist_id: 6,
  },
  {
    song: 'Silence',
    artist: 'Delerium ft. Sarah McLachlan',
    album: 'Karma',
    rating: 4,
    playlist_id: 4,
  },
  {
    song: 'Children',
    artist: 'Robert Miles',
    album: 'Dreamland',
    rating: 2,
    playlist_id: 2,
  },
  {
    song: 'Sandstorm',
    artist: 'Darude',
    album: 'Before the Storm',
    rating: 3,
    playlist_id: 9,
  },
  {
    song: 'Café Del Mar',
    artist: 'Energy 52',
    album: 'Café Del Mar',
    rating: 5,
    playlist_id: 3,
  },
  {
    song: '9 PM (Till I Come)',
    artist: 'ATB',
    album: "Movin' Melodies",
    rating: 1,
    playlist_id: 7,
  },
  {
    song: 'Insomnia',
    artist: 'Faithless',
    album: 'Reverence',
    rating: 4,
    playlist_id: 8,
  },
  {
    song: 'Greece 2000',
    artist: 'Three Drives On A Vinyl',
    album: 'Greece 2000',
    rating: 5,
    playlist_id: 1,
  },
  {
    song: 'Better Off Alone',
    artist: 'Alice Deejay',
    album: 'Who Needs Guitars Anyway?',
    rating: 3,
    playlist_id: 10,
  },
  {
    song: 'Ecstasy',
    artist: 'ATB',
    album: 'No Silence',
    rating: 2,
    playlist_id: 5,
  },
  {
    song: 'Synaesthesia (Fly Away)',
    artist: 'The Thrillseekers',
    album: 'Synaesthesia (Fly Away)',
    rating: 5,
    playlist_id: 6,
  },
  {
    song: 'Beachball',
    artist: 'Nalin & Kane',
    album: 'Beachball',
    rating: 3,
    playlist_id: 4,
  },
  {
    song: 'For An Angel',
    artist: 'Paul van Dyk',
    album: '45 RPM',
    rating: 4,
    playlist_id: 9,
  },
  {
    song: 'Saltwater',
    artist: 'Chicane ft. Moya Brennan',
    album: 'Behind the Sun',
    rating: 2,
    playlist_id: 2,
  },
  {
    song: 'The Launch',
    artist: 'DJ Jean',
    album: 'The Launch',
    rating: 5,
    playlist_id: 8,
  },
  {
    song: 'Bellissima',
    artist: 'DJ Quicksilver',
    album: 'Quicksilver',
    rating: 4,
    playlist_id: 7,
  },
  {
    song: 'Out of the Blue',
    artist: 'System F',
    album: 'Out of the Blue',
    rating: 3,
    playlist_id: 5,
  },
  {
    song: 'Everytime You Need Me',
    artist: 'Fragma ft. Maria Rubia',
    album: 'Toca',
    rating: 1,
    playlist_id: 10,
  },
  {
    song: "L'Esperanza",
    artist: 'Sven Väth',
    album: 'Accident in Paradise',
    rating: 2,
    playlist_id: 1,
  },
  {
    song: 'The Way',
    artist: 'Divine Inspiration',
    album: 'The Way',
    rating: 4,
    playlist_id: 3,
  },
  {
    song: 'Pulsar',
    artist: 'Mauro Picotto',
    album: 'The Album',
    rating: 5,
    playlist_id: 6,
  },
  {
    song: 'Smells Like Teen Spirit',
    artist: 'Nirvana',
    album: 'Nevermind',
    rating: 5,
    playlist_id: 7,
  },
  {
    song: 'Imagine',
    artist: 'John Lennon',
    album: 'Imagine',
    rating: 3,
    playlist_id: 5,
  },
  {
    song: 'Hotel California',
    artist: 'Eagles',
    album: 'Hotel California',
    rating: 5,
    playlist_id: 4,
  },
  {
    song: 'Hey Jude',
    artist: 'The Beatles',
    album: 'Hey Jude',
    rating: 4,
    playlist_id: 9,
  },
  {
    song: 'Stairway to Heaven',
    artist: 'Led Zeppelin',
    album: 'Led Zeppelin IV',
    rating: 5,
    playlist_id: 2,
  },
  {
    song: 'Thriller',
    artist: 'Michael Jackson',
    album: 'Thriller',
    rating: 5,
    playlist_id: 6,
  },
  {
    song: 'Billie Jean',
    artist: 'Michael Jackson',
    album: 'Thriller',
    rating: 4,
    playlist_id: 3,
  },
  {
    song: 'Like a Rolling Stone',
    artist: 'Bob Dylan',
    album: 'Highway 61 Revisited',
    rating: 4,
    playlist_id: 8,
  },
  {
    song: "Sweet Child o' Mine",
    artist: "Guns N' Roses",
    album: 'Appetite for Destruction',
    rating: 5,
    playlist_id: 10,
  },
  {
    song: "Boys Don't Cry",
    artist: 'The Cure',
    album: "Boys Don't Cry",
    rating: 3,
    playlist_id: 1,
  },
  {
    song: 'Purple Haze',
    artist: 'Jimi Hendrix',
    album: 'Are You Experienced',
    rating: 5,
    playlist_id: 5,
  },
  {
    song: 'Hallelujah',
    artist: 'Leonard Cohen',
    album: 'Various Positions',
    rating: 4,
    playlist_id: 7,
  },
  {
    song: 'Wonderwall',
    artist: 'Oasis',
    album: "(What's the Story) Morning Glory?",
    rating: 4,
    playlist_id: 3,
  },
  {
    song: 'Wish You Were Here',
    artist: 'Pink Floyd',
    album: 'Wish You Were Here',
    rating: 5,
    playlist_id: 9,
  },
  {
    song: 'Like a Prayer',
    artist: 'Madonna',
    album: 'Like a Prayer',
    rating: 4,
    playlist_id: 2,
  },
  {
    song: "Livin' on a Prayer",
    artist: 'Bon Jovi',
    album: 'Slippery When Wet',
    rating: 5,
    playlist_id: 8,
  },
  {
    song: 'Another Brick in the Wall (Part II)',
    artist: 'Pink Floyd',
    album: 'The Wall',
    rating: 5,
    playlist_id: 4,
  },
  {
    song: 'Crazy',
    artist: 'Gnarls Barkley',
    album: 'St. Elsewhere',
    rating: 4,
    playlist_id: 10,
  },
  {
    song: 'Lose Yourself',
    artist: 'Eminem',
    album: '8 Mile Soundtrack',
    rating: 5,
    playlist_id: 1,
  },
  {
    song: 'Hurt',
    artist: 'Johnny Cash',
    album: 'American IV: The Man Comes Around',
    rating: 5,
    playlist_id: 6,
  },
  {
    song: 'Yesterday',
    artist: 'The Beatles',
    album: 'Help!',
    rating: 4,
    playlist_id: 3,
  },
  {
    song: 'Purple Rain',
    artist: 'Prince',
    album: 'Purple Rain',
    rating: 5,
    playlist_id: 9,
  },
  {
    song: 'I Will Always Love You',
    artist: 'Whitney Houston',
    album: 'The Bodyguard Soundtrack',
    rating: 5,
    playlist_id: 2,
  },
  {
    song: 'The Sound of Silence',
    artist: 'Simon & Garfunkel',
    album: 'Wednesday Morning, 3 A.M.',
    rating: 4,
    playlist_id: 8,
  },
  {
    song: 'Wonderful Tonight',
    artist: 'Eric Clapton',
    album: 'Slowhand',
    rating: 5,
    playlist_id: 5,
  },
  {
    song: 'Under the Bridge',
    artist: 'Red Hot Chili Peppers',
    album: 'Blood Sugar Sex Magik',
    rating: 5,
    playlist_id: 1,
  },
  {
    song: "Don't Stop Believin'",
    artist: 'Journey',
    album: 'Escape',
    rating: 4,
    playlist_id: 7,
  },
  {
    song: 'Every Breath You Take',
    artist: 'The Police',
    album: 'Synchronicity',
    rating: 4,
    playlist_id: 10,
  },
  {
    song: 'No Woman, No Cry',
    artist: 'Bob Marley & The Wailers',
    album: 'Natty Dread',
    rating: 5,
    playlist_id: 2,
  },
  {
    song: 'Sweet Caroline',
    artist: 'Neil Diamond',
    album: "Brother Love's Travelling Salvation Show",
    rating: 4,
    playlist_id: 6,
  },
  {
    song: 'Hound Dog',
    artist: 'Elvis Presley',
    album: "Elvis' Golden Records",
    rating: 5,
    playlist_id: 3,
  },
  {
    song: 'Stand by Me',
    artist: 'Ben E. King',
    album: "Don't Play That Song!",
    rating: 4,
    playlist_id: 9,
  },
  {
    song: 'I Want to Hold Your Hand',
    artist: 'The Beatles',
    album: 'Meet The Beatles!',
    rating: 3,
    playlist_id: 4,
  },
  {
    song: "Don't Let the Sun Go Down on Me",
    artist: 'Elton John',
    album: 'Caribou',
    rating: 5,
    playlist_id: 1,
  },
  {
    song: 'Every Rose Has Its Thorn',
    artist: 'Poison',
    album: 'Open Up and Say... Ahh!',
    rating: 3,
    playlist_id: 7,
  },
  {
    song: 'September',
    artist: 'Earth, Wind & Fire',
    album: 'The Best of Earth, Wind & Fire, Vol. 1',
    rating: 5,
    playlist_id: 5,
  },
  {
    song: 'Let It Be',
    artist: 'The Beatles',
    album: 'Let It Be',
    rating: 4,
    playlist_id: 10,
  },
  {
    song: 'I Will Survive',
    artist: 'Gloria Gaynor',
    album: 'Love Tracks',
    rating: 4,
    playlist_id: 2,
  },
  {
    song: 'Eye of the Tiger',
    artist: 'Survivor',
    album: 'Eye of the Tiger',
    rating: 4,
    playlist_id: 8,
  },
  {
    song: 'Johnny B. Goode',
    artist: 'Chuck Berry',
    album: 'Chuck Berry Is on Top',
    rating: 5,
    playlist_id: 3,
  },
  {
    song: 'Imagine',
    artist: 'Ariana Grande',
    album: 'Imagine - Single',
    rating: 3,
    playlist_id: 6,
  },
  {
    song: "Ain't No Mountain High Enough",
    artist: 'Marvin Gaye & Tammi Terrell',
    album: 'United',
    rating: 5,
    playlist_id: 1,
  },
  {
    song: 'Dream On',
    artist: 'Aerosmith',
    album: 'Aerosmith',
    rating: 4,
    playlist_id: 4,
  },
  {
    song: 'Piano Man',
    artist: 'Billy Joel',
    album: 'Piano Man',
    rating: 5,
    playlist_id: 9,
  },
  {
    song: 'The Boxer',
    artist: 'Simon & Garfunkel',
    album: 'Bridge Over Troubled Water',
    rating: 4,
    playlist_id: 2,
  },
  {
    song: "Let's Get It On",
    artist: 'Marvin Gaye',
    album: "Let's Get It On",
    rating: 5,
    playlist_id: 7,
  },
  {
    song: 'With or Without You',
    artist: 'U2',
    album: 'The Joshua Tree',
    rating: 5,
    playlist_id: 10,
  },
  {
    song: 'Smooth',
    artist: 'Santana feat. Rob Thomas',
    album: 'Supernatural',
    rating: 4,
    playlist_id: 1,
  },
];

const seedSongLib = () => SongLib.bulkCreate(songData);

module.exports = seedSongLib;
